formatter: markdown table

header-from: README.md
footer-from: ""

sections:
  hide: []
  show:
    - header
    - inputs
    - outputs
    - requirements
    - providers

content: |
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Requirements }}

  {{ .Providers }}

output:
  file: README.md
  mode: inject
  template: |
    {{ .Content }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
