name: Generate terraform docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  terraform-docs:
    uses: actionsforge/actions/.github/workflows/terraform-docs.yml@main
